/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: cd339f246bfed4cfab1b5b069d872a2f)
interface __BaseEnv_Env {
	items: D1Database;
	ASSETS: Fetcher;
	WEBAUTHN_APP_NAME: "sisig";
	SYNCED_STATE_SERVER: DurableObjectNamespace<import("./src/worker").SyncedStateServer>;
	SESSION_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").SessionDurableObject>;
	PASSKEY_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").PasskeyDurableObject>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "SyncedStateServer" | "PasskeyDurableObject";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WEBAUTHN_APP_NAME">> {}
}
