/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 07550feeedae7087ccdee98fee299e5f)
interface __BaseEnv_Env {
	items: D1Database;
	ASSETS: Fetcher;
	SYNCED_STATE_SERVER: DurableObjectNamespace<import("./src/worker").SyncedStateServer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "SyncedStateServer";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
