/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c4976c29f93326409635255dfbc7205b)
interface __BaseEnv_Env {
	items: D1Database;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
